export { registry } from '../utils/registry';

// schema definitions for OPENAPI producing (side-effect only — registers with registry)
export * from '../utils/common';
import './agreement/schema';
import './brand/schema';
import './cart/schema';
import './category/schema';
import './company/schema';
import './module/schema';
import './contact/schema';
import './google/schema';
import './gsm/schema';
import './header-menu/schema';
import './order/schema';
import './page/schema';
import './payment-iyzico/schema';
import './post/schema';
import './product/schema';
import './product-variant/schema';
import './question/schema';
import './review/schema';
import './geliver/schema';
import './traffic/schema';
import './translation/schema';
import './user/schema';

// Validation defines using for backend and frontend validation middleware
export * from './address/validation';
export * from './agreement/validation';
export * from './auth/validation';
export * from './brand/validation';
export * from './cart/validation';
export * from './category/validation';
export * from './company/validation';
export * from './module/validation';
export * from './contact/validation';
export * from './google/validation';
export * from './gsm/validation';
export * from './header-menu/validation';
export * from './minio/bucket/validation';
export * from './minio/object/validation';
export * from './order/validation';
export * from './page/validation';
export * from './payment-iyzico/validation';
export * from './post/validation';
export * from './product/validation';
export * from './product-variant/validation';
export * from './question/validation';
export * from './review/validation';
export * from './geliver/validation';
export * from './traffic/validation';
export * from './translation/validation';
export * from './user/validation';

// Path defines — only register for OPENAPI producing
import './auth/route';
import './address/route';
import './agreement/route';
import './brand/route';
import './cart/route';
import './category/route';
import './company/route';
import './country/route';
import './currency/route';
import './module/route';
import './contact/route';
import './google/route';
import './gsm/route';
import './header-menu/route';
import './minio/bucket/route';
import './minio/object/route';
import './order/route';
import './page/route';
import './payment-iyzico/route';
import './post/route';
import './product/route';
import './product-variant/route';
import './question/route';
import './review/route';
import './geliver/route';
import './traffic/route';
import './translation/route';
import './user/route';
