import type { z } from 'zod';
import type { PaginationQuerySchema, ApiErrorSchema } from '../schemas/common';

export type PaginationQuery = z.infer<typeof PaginationQuerySchema>;
export type ApiError = z.infer<typeof ApiErrorSchema>;

export * from '../schemas/address/schema';
export * from '../schemas/cart/schema';
export * from '../schemas/company/schema';
export * from '../schemas/contact/schema';
export * from '../schemas/country/schema';
export * from '../schemas/currency/schema';
export * from './module';
export * from '../schemas/gsm/schema';
export * from '../schemas/header-menu/schema';
export * from './iyzico';
export * from './menu';
export * from '../schemas/minio/schema';
export * from './order';
export * from './page';
export * from './post';
export * from './props';
export * from './geliver';
export * from '../schemas/google/schema';
export * from './question';
export * from './review';
export * from './search';
export * from './translation';
export * from '../schemas/agreement/schema';
export * from '../schemas/auth/schema';
export * from '../schemas/brand/schema';
export * from '../schemas/category/schema';
export * from './common';
export * from './product';
export * from './traffic';
export * from './user';
export * from './validation';
export * from './variant';
export * from './yandex';
