import type { z } from 'zod';
import type { PaginationQuerySchema, ApiErrorSchema } from '../modules/common';

export type PaginationQuery = z.infer<typeof PaginationQuerySchema>;
export type ApiError = z.infer<typeof ApiErrorSchema>;

export * from '../modules/address/schema';
export * from '../modules/cart/schema';
export * from '../modules/company/schema';
export * from '../modules/contact/schema';
export * from '../modules/country/schema';
export * from '../modules/currency/schema';
export * from '../modules/module/schema';
export * from '../modules/gsm/schema';
export * from '../modules/header-menu/schema';
export * from '../modules/payment-iyzico/schema';
export * from './menu';
export * from '../modules/minio/schema';
export * from '../modules/order/schema';
export * from '../modules/page/schema';
export * from '../modules/post/schema';
export * from './props';
export * from '../modules/geliver/schema';
export * from '../modules/google/schema';
export * from '../modules/question/schema';
export * from '../modules/review/schema';
export * from './search';
export * from '../modules/translation/schema';
export * from '../modules/agreement/schema';
export * from '../modules/auth/schema';
export * from '../modules/brand/schema';
export * from '../modules/category/schema';
export * from './common';
export * from '../modules/product/schema';
export * from '../modules/traffic/schema';
export * from '../modules/user/schema';
export * from './validation';
export * from '../modules/product-variant/schema';
export * from './yandex';
