import type { z } from 'zod';
import type { PaginationQuerySchema, ApiErrorSchema } from '../schemas';

export type PaginationQuery = z.infer<typeof PaginationQuerySchema>;
export type ApiError = z.infer<typeof ApiErrorSchema>;

export * from './address';
export * from './cart';
export * from './company';
export * from './contact';
export * from './country';
export * from './currency';
export * from './external';
export * from './gsm';
export * from './iyzico';
export * from './menu';
export * from './minio';
export * from './order';
export * from './post';
export * from './props';
export * from './geliver';
export * from './google';
export * from './question';
export * from './review';
export * from './search';
export * from './translation';
export * from './agreement';
export * from './auth';
export * from './brand';
export * from './card';
export * from './category';
export * from './common';
export * from './product';
export * from './traffic';
export * from './user';
export * from './validation';
export * from './variant';
export * from './yandex';
