export { registry } from './registry';

// schema definitions for OPENAPI producing (side-effect only — registers with registry)
export * from './common';
import './auth/schema';
import './address/schema';
import './agreement/schema';
import './brand/schema';
import './cart/schema';
import './category/schema';
import './company/schema';
import './external/schema';
import './form/schema';
import './google/schema';
import './gsm/schema';
import './minio/bucket/schema';
import './minio/object/schema';
import './order/schema';
import './payment-iyzico/schema';
import './post/schema';
import './product/schema';
import './product-variant/schema';
import './question/schema';
import './review/schema';
import './shipping/schema';
import './traffic/schema';
import './translation/schema';
import './user/schema';

// Validation defines using for backend and frontend validation middleware
export * from './address/validation';
export * from './agreement/validation';
export * from './auth/validation';
export * from './brand/validation';
export * from './cart/validation';
export * from './category/validation';
export * from './company/validation';
export * from './external/validation';
export * from './form/validation';
export * from './google/validation';
export * from './gsm/validation';
export * from './minio/bucket/validation';
export * from './minio/object/validation';
export * from './order/validation';
export * from './payment-iyzico/validation';
export * from './post/validation';
export * from './product/validation';
export * from './product-variant/validation';
export * from './question/validation';
export * from './review/validation';
export * from './shipping/validation';
export * from './traffic/validation';
export * from './translation/validation';
export * from './user/validation';

// Path defines — only register for OPENAPI producing
import './auth/route';
import './address/route';
import './agreement/route';
import './brand/route';
import './card/route';
import './cart/route';
import './category/route';
import './company/route';
import './countries/route';
import './currency/route';
import './external/route';
import './form/route';
import './google/route';
import './gsm/route';
import './minio/bucket/route';
import './minio/object/route';
import './order/route';
import './payment-iyzico/route';
import './post/route';
import './product/route';
import './product-variant/route';
import './question/route';
import './review/route';
import './shipping/route';
import './traffic/route';
import './translation/route';
import './user/route';
